Repository shonilbhide/dollar_bot, pull requests merged in 2023-10, with the labels that each got.

#5 PR changes from Issue3_bug to dev
  code/pdf.py
Labels: bug

#17 Merge code changes from Issue_9_Enhancement to dev
  code/add_user.py
  code/code.py
  code/helper.py
Labels: enhancement

#20 Merge code changes from Issue_16_Enhancement to Dev
  code/add.py
  code/add_category.py
  code/add_user.py
  code/code.py
  code/delete_expense.py
  code/helper.py
  code/history.py
  code/pdf.py
  docs/add.md
  docs/add_category.md
  docs/history.md
  python_docs/code.html
  user.properties
Labels: enhancement

#21 PR code changes from Issue 15 enhancement to dev
  code/pdf.py
Labels: enhancement

#26 Issue 19 enhancement to Dev
  code/add.py
  code/code.py
  code/delete_user.py
  code/helper.py
  code/pdf.py
Labels: enhancement

#27 Release 1
  code/add.py
  code/add_user.py
  code/code.py
  code/delete_user.py
  code/helper.py
  code/pdf.py
Labels: Release

#32 PR code changes from Issue 23 enhancement to dev
  code/pdf.py
Labels: enhancement

#34 Issue_31_Bug: Modified the budget functionality. to dev
  code/budget.py
  code/budget_delete.py
  code/budget_update.py
  code/budget_view.py
  code/pdf.py
Labels: bug

#35 PR code changes from Issue33_Enhancement to dev
  code/pdf.py
Labels: enhancement

#39 Merge code changes from Issue 24 enhancement to dev
  code/code.py
  code/helper.py
  code/send_mail.py
Labels: enhancement

#42 PR changes from Issue_41_Documentation to dev
  requirements.txt
Labels: documentation

#44 PR changes from Issue_43_Documentation to dev
  README.md
Labels: documentation

#45 PR changes from Issue_43_Documentation to dev
  README.md
Labels: documentation

#48 PR changes from Issue_47_documentation to dev
  README.md
Labels: documentation

#49 Issue47-modified why should you use DollarSplitBot
  README.md
Labels: documentation

#50 Issue-47-Docs why
  README.md
Labels: documentation

#56 Merge changes from Issue 54 documentation to dev
  README.md
Labels: documentation

#62 Issue 60 documentation
  README.md
  docs/Update_Version.pdf
Labels: documentation

#63 Added style chekker
  .pylintrc
Labels: documentation

#69 PR changes from Issue_68_Documentation to dev
  README.md
Labels: documentation

#77 Added Automated Analysis Tools
  README.md
Labels: documentation

#78 Link to chat channel added
  README.md
Labels: documentation

#79 Version Specifications added to READme
  README.md
Labels: documentation

#80 All users and Projects added
  README.md
Labels: documentation

#81 Issue 75 documentation
  README.md
Labels: documentation

#82 Added Depreciated Libraries
  README.md
Labels: documentation

#83 PR changes from Issue_71_documentation to dev
  docs/add_category.md
Labels: documentation

#70 PR changes from Issue_68_Documentation to dev
  README.md
Labels: documentation

#86 PR changes from Issue_71_documentation to dev
  code/code.py
  docs/add.md
Labels: documentation

#88 PR changes from Issue_87_Documentation to dev
  docs/add.md
  docs/add_user.md
Labels: documentation

#89 Merge RUBRICS to dev
  RUBRICS.md
Labels: documentation

#93 PR changes from Issue_87_Documentation to dev
  docs/csvfile.md
Labels: documentation

#94 Issue 92 documentation
  docs/budget_delete.md
  docs/budget_update.md
Labels: documentation

#96 PR changes from Issue_87_Documentation to dev
  docs/csvfile.md
Labels: documentation

#97 PR changes from Issue_87_documentation to dev
  docs/add.md
  docs/add_category.md
  docs/add_user.md
  docs/delete_expense.md
Labels: documentation

#98 PR changes from Issue_87_documentation to dev
  docs/delete_user.md
Labels: documentation

#99 PR changes from Issue_87_Documentation to dev
  docs/delete.md
  docs/display.md
  docs/edit.md
  docs/estimate.md
Labels: documentation

#100 Issue 92 documentation
  docs/budget.md
  docs/send_file.md
Labels: documentation

#102 PR changes from Issue_87_Documentation to dev
  code/pdf.py
Labels: documentation

#103 All PR changes from dev to main
  .circleci/config.yml
  .pylintrc
  .travis.yml
  CSC510 Group 32 - DollarSplitBot.csv
  README.md
  RUBRICS.md
  TROUBLESHOOTING.md
  code/add.py
  code/add_category.py
  code/add_user.py
  code/budget.py
  code/budget_delete.py
  code/budget_update.py
  code/budget_view.py
  code/code.py
  code/helper.py
  code/pdf.py
  docs/Update_Version.pdf
  docs/add.md
  docs/add_category.md
  docs/add_user.md
  docs/budget.md
  docs/budget_delete.md
  docs/budget_update.md
  docs/csvfile.md
  docs/delete.md
  docs/delete_expense.md
  docs/delete_user.md
  docs/display.md
  docs/edit.md
  docs/estimate.md
  docs/send_file.md
  project_key
  project_key.pub
  test/test_add.py
Labels: documentation, enhancement
